import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Keyboard, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { getChannels } from "../api";
import { claimTask, createTask, getServerComputers, getServerMembers, getServerTasks, getWikiDirectory, getWikiStatus, refreshWiki, setTaskStatus, updateServerComputer, type MobileComputer, type MobileMember, type MobileTask, type WikiArtifact } from "../stage3Api";
import { STAGE3_ROUTES, type Stage3Route } from "../stage3Navigation";

type Props = { serverId: string };

function ErrorText({ message }: { message: string | null }) { return message ? <Text style={styles.error}>{message}</Text> : null; }

export function Stage3Navigator({ serverId }: Props) {
  const [route, setRoute] = useState<Stage3Route>("tasks");
  return <View style={styles.root}>
    <View style={styles.body}>
      {route === "tasks" ? <TasksPanel serverId={serverId} />
        : route === "wiki" ? <WikiPanel serverId={serverId} />
          : route === "members" ? <MembersPanel serverId={serverId} />
            : <ComputersPanel serverId={serverId} />}
    </View>
    <View style={styles.tabs} accessibilityRole="tablist">
      {STAGE3_ROUTES.map(({ route: key, title }) => <Pressable key={key} accessibilityRole="tab" accessibilityState={{ selected: route === key }} accessibilityLabel={title} onPress={() => setRoute(key)} style={styles.tab}><Text style={[styles.tabText, route === key && styles.selected]}>{title}</Text></Pressable>)}
    </View>
  </View>;
}

function TasksPanel({ serverId }: Props) {
  const [rows, setRows] = useState<MobileTask[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState<string | null>(null);
  const [channels, setChannels] = useState<Array<{ id: string; name?: string | null; type?: string }>>([]);
  const [createOpen, setCreateOpen] = useState(false); const [title, setTitle] = useState(""); const [channelId, setChannelId] = useState<string | null>(null); const [mutating, setMutating] = useState<string | null>(null);
  const load = useCallback(async () => { setBusy(true); setError(null); try { setRows((await getServerTasks(serverId)).tasks); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }, [serverId]);
  useEffect(() => { void load(); }, [load]);
  const openCreate = async () => { setError(null); try { const available = (await getChannels(serverId)).filter((item) => item.type !== "dm" && item.type !== "thread" && item.joined !== false && !item.archivedAt); setChannels(available); setChannelId(available[0]?.id ?? null); setTitle(""); setCreateOpen(true); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const submitCreate = async () => { if (!channelId || !title.trim()) return; setMutating("create"); setError(null); try { const result = await createTask(serverId, channelId, title.trim()); setRows((current) => [...current, ...(result.tasks ?? [])]); setCreateOpen(false); setTitle(""); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setMutating(null); } };
  const mutateTask = async (item: MobileTask, action: "claim" | MobileTask["status"]) => { setMutating(item.id); setError(null); try { const result = action === "claim" ? await claimTask(serverId, item.id) : await setTaskStatus(serverId, item.id, action); setRows((current) => current.map((row) => row.id === item.id ? result.task : row)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setMutating(null); } };
  const statusAction = (status: MobileTask["status"]) => status === "todo" ? "in_progress" : status === "in_progress" ? "in_review" : status === "in_review" ? "done" : status === "done" ? "closed" : "todo";
  return <View style={styles.panel}><View style={styles.header}><Text style={styles.title}>任务</Text><View style={styles.headerActions}><Pressable accessibilityRole="button" accessibilityLabel="新建任务" onPress={() => void openCreate()}><Text style={styles.action}>新建</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="刷新任务" onPress={() => void load()}><Text style={styles.action}>刷新</Text></Pressable></View></View><ErrorText message={error} />{busy ? <ActivityIndicator /> : <FlatList data={rows} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>暂无任务</Text>} renderItem={({ item }) => { const next = statusAction(item.status); return <View style={styles.card}><Text style={styles.meta}>task #{item.taskNumber}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.meta}>{item.status}{item.claimedByName ? ` · ${item.claimedByName}` : ""}</Text>{item.description ? <Text style={styles.bodyText}>{item.description}</Text> : null}<View style={styles.cardActions}>{!item.claimedById ? <Pressable accessibilityRole="button" accessibilityLabel={`认领任务 ${item.taskNumber}`} disabled={mutating === item.id} onPress={() => void mutateTask(item, "claim")}><Text style={styles.action}>{mutating === item.id ? "处理中…" : "认领"}</Text></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel={`任务 ${item.taskNumber} 移至 ${next}`} disabled={mutating === item.id} onPress={() => void mutateTask(item, next)}><Text style={styles.action}>移至 {next}</Text></Pressable></View></View>; }} />}
    <Modal visible={createOpen} transparent animationType="slide" onRequestClose={() => setCreateOpen(false)}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>新建任务</Text><TextInput autoFocus value={title} onChangeText={setTitle} placeholder="任务标题" accessibilityLabel="任务标题" style={styles.modalInput} /><Text style={styles.meta}>选择频道</Text><View style={styles.channelChoices}>{channels.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityState={{ selected: channelId === item.id }} onPress={() => setChannelId(item.id)} style={[styles.channelChoice, channelId === item.id && styles.channelChoiceSelected]}><Text>{item.name || item.id}</Text></Pressable>)}</View><View style={styles.modalActions}><Pressable accessibilityRole="button" onPress={() => setCreateOpen(false)}><Text style={styles.action}>取消</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="确认新建任务" disabled={!channelId || !title.trim() || mutating === "create"} onPress={() => void submitCreate()}><Text style={[styles.action, (!channelId || !title.trim() || mutating === "create") && styles.disabledText]}>{mutating === "create" ? "创建中…" : "创建"}</Text></Pressable></View></View></View></Modal>
  </View>;
}

function WikiPanel({ serverId }: Props) {
  const [status, setStatus] = useState<string>("加载中"); const [rows, setRows] = useState<WikiArtifact[]>([]); const [error, setError] = useState<string | null>(null); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { setError(null); try { const current = await getWikiStatus(serverId); const value = current.space?.status ?? "不可用"; setStatus(value); if (value !== "不可用") { const directory = await getWikiDirectory(serverId); setRows(directory.pages ?? []); } else setRows([]); } catch (e) { setStatus("不可用"); setRows([]); setError(e instanceof Error ? e.message : String(e)); } }, [serverId]);
  useEffect(() => { void load(); }, [load]);
  const triggerRefresh = async () => { setRefreshing(true); setError(null); try { await refreshWiki(serverId); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setRefreshing(false); } };
  return <View style={styles.panel}><View style={styles.header}><Text style={styles.title}>Wiki</Text><Pressable accessibilityRole="button" accessibilityLabel="刷新Wiki" disabled={refreshing} onPress={() => void triggerRefresh()}><Text style={[styles.action, refreshing && styles.disabledText]}>{refreshing ? "刷新中…" : "刷新"}</Text></Pressable></View><Text style={styles.meta}>状态：{status}</Text><ErrorText message={error} /><FlatList data={rows} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>暂无可用 Wiki 页面</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.cardTitle}>{item.title}</Text>{item.summary ? <Text style={styles.bodyText}>{item.summary}</Text> : null}</View>} /></View>;
}

function MembersPanel({ serverId }: Props) {
  const [rows, setRows] = useState<MobileMember[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; getServerMembers(serverId).then((items) => { if (!cancelled) setRows(items); }).catch((e) => { if (!cancelled) setError(e instanceof Error ? e.message : String(e)); }); return () => { cancelled = true; }; }, [serverId]);
  return <View style={styles.panel}><Text style={styles.title}>成员</Text><ErrorText message={error} /><FlatList data={rows} keyExtractor={(item) => item.userId} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>暂无成员</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.cardTitle}>{item.displayName || item.name}</Text><Text style={styles.meta}>{item.role}</Text>{item.description ? <Text style={styles.bodyText}>{item.description}</Text> : null}</View>} /></View>;
}

function ComputersPanel({ serverId }: Props) {
  const [rows, setRows] = useState<MobileComputer[]>([]); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<MobileComputer | null>(null); const [name, setName] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(null); try { setRows(await getServerComputers(serverId)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }, [serverId]);
  useEffect(() => { void load(); }, [load]);
  const saveName = async () => { if (!editing || !name.trim()) return; setBusy(true); setError(null); try { const updated = await updateServerComputer(serverId, editing.id, { name: name.trim() }); setRows((current) => current.map((row) => row.id === updated.id ? updated : row)); setEditing(null); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  return <View style={styles.panel}><View style={styles.header}><Text style={styles.title}>电脑</Text><Pressable accessibilityRole="button" accessibilityLabel="刷新电脑" onPress={() => void load()}><Text style={styles.action}>刷新</Text></Pressable></View><ErrorText message={error} /><FlatList data={rows} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>暂无电脑</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.meta}>{item.status} · {item.os || "系统未知"}</Text>{item.hostname ? <Text style={styles.bodyText}>{item.hostname}</Text> : null}<View style={styles.cardActions}><Pressable accessibilityRole="button" accessibilityLabel={`重命名电脑 ${item.name}`} onPress={() => { setEditing(item); setName(item.name); }}><Text style={styles.action}>重命名</Text></Pressable></View></View>} /><Modal visible={Boolean(editing)} transparent animationType="slide" onRequestClose={() => setEditing(null)}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>重命名电脑</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder="电脑名称" accessibilityLabel="电脑名称" returnKeyType="done" blurOnSubmit onSubmitEditing={() => void saveName()} style={styles.modalInput} /><View style={styles.modalActions}><Pressable accessibilityRole="button" onPress={() => setEditing(null)}><Text style={styles.action}>取消</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="确认重命名电脑" disabled={!name.trim() || busy} onPress={() => void saveName()}><Text style={[styles.action, (!name.trim() || busy) && styles.disabledText]}>{busy ? "保存中…" : "保存"}</Text></Pressable></View></View></View></Modal></View>;
}

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#F6F8FB" }, body: { flex: 1 }, panel: { flex: 1, padding: 16 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, headerActions: { flexDirection: "row", gap: 14 }, title: { fontSize: 24, fontWeight: "700", color: "#17212F", marginBottom: 10 }, action: { color: "#365FE8" }, disabledText: { opacity: 0.4 }, list: { gap: 8, paddingVertical: 8 }, card: { padding: 12, borderRadius: 10, borderWidth: 1, borderColor: "#E5EAF0", backgroundColor: "#FFF" }, cardTitle: { color: "#17212F", fontWeight: "700" }, cardActions: { flexDirection: "row", gap: 16, marginTop: 10 }, meta: { color: "#718096", fontSize: 12, marginTop: 4 }, bodyText: { color: "#4A5568", marginTop: 6 }, empty: { color: "#718096", textAlign: "center", padding: 24 }, error: { color: "#C53030", marginBottom: 8 }, tabs: { flexDirection: "row", paddingVertical: 8, borderTopWidth: 1, borderTopColor: "#E5EAF0", backgroundColor: "#FFF" }, tab: { flex: 1, alignItems: "center", paddingVertical: 8 }, tabText: { color: "#718096" }, selected: { color: "#365FE8", fontWeight: "700" }, modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.3)" }, modalCard: { backgroundColor: "#FFF", padding: 20, borderTopLeftRadius: 16, borderTopRightRadius: 16 }, modalTitle: { color: "#17212F", fontSize: 20, fontWeight: "700", marginBottom: 14 }, modalInput: { borderWidth: 1, borderColor: "#E5EAF0", borderRadius: 8, padding: 10, color: "#17212F", marginBottom: 14 }, channelChoices: { gap: 8, marginVertical: 8 }, channelChoice: { padding: 10, borderRadius: 8, backgroundColor: "#F6F8FB" }, channelChoiceSelected: { borderWidth: 1, borderColor: "#365FE8", backgroundColor: "#E8EEFF" }, modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 18, marginTop: 14 } });
